<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Promise api介绍</title>
</head>

<body>
  <script>
    /**
     * 静态方法:
     * - all
     * - race
     * - reject
     * - resolve
     * - allSettled: t39第四阶段草案（draft）.
     * 
     * 实例方法:
     * - then
     * - catch
     * - finally
     */

    // 定义3个promise.
    const p1 = Promise.resolve('success');
    const p2 = Promise.reject('failed');
    const p3 = new Promise((resolve, reject) => setTimeout(reject, 1000));
    const promises = [p1, p2, p3];

    /**
     * 1. Promise.resolve
     * 返回一个promise, 执行成功的回调
     */
    //  p1.then(result => {
    //   console.log(result);
    //  }, err => {
    //    // 未被调用
    //  });

    /**
     * 2. Promise.reject
     * 返回一个promise, 执行失败的回调
     */
    //  p2.then(result => {
    //    // 未被调用
    //  }, err => {
    //   console.log(err)
    //  });

    /**
     * 3. Promise.all
     * 返回一个promise, 
     * - 如果参数中所有都执行成功，那么此实例执行成功的回调
     * - 如果参数中有一个执行失败, 那么此实例立即执行失败的回调. 失败的原因是第一个promise失败的结果.
     */
    // Promise.all(promises).then(results => {
    //   console.log(results);
    //   // 此处未执行
    // }, err => {
    //   console.log(err);
    // })

    /**
     * 4. Promise.race
     * 返回一个promise，一旦参数中某个promise执行成功或失败, 就立即执行对于的回调.
     */
    // Promise.race(promises).then(results => {
    //   console.log(results);
    // }, err => {
    //   // 此处未执行
    //   console.log(err);
    // })


    /**
     * 5. Promise.allSettled
     * 返回一个promise对象, 给定的所有promise都被成功解析或被失败解析，并且每个对象都描述每个promise的结果
     */
    // Promise.allSettled(promises).then(results => {
    //   // 输出结果:
    //   // - fulfilled
    //   // - reject
    //   // - reject
    //   results.forEach(m => console.log(m.status));
    // })

    /**
    * 6. 实例方法
    * - then: 接收两个参数, 执行成功或失败的回调.
    * - finally: 无论promise执行成功与否, 都会执行的回调.
    * - catch: promise执行失败后的回调.
    * 返回一个promise对象, 给定的所有promise都被成功解析或被失败解析，并且每个对象都描述每个promise的结果
    */
    p1.then(result => {
      console.log(result + '- 01')
      return result;
    }, err => {
      // 未被执行
      console.log(err);
    }).then(result => {
      console.log(result + '- 02')

      // 等同于第一个then上的直接返回. return result.
      return Promise.resolve(result);
    }, err => {
      // 未被执行
      console.log(err);
    }).then(result => {
      console.log(result + '- 03')

      // 如果要执行失败的回调，需要显示的返回一个reject.
      return Promise.reject(result);
    }, err => {
      // 未被执行, 前面的reject会被后面的then或catch接收
      console.log(err);
    }).then(result => {
      // 未被执行.
      console.log(result + '04');
    }, err => {
      // 失败执行了.
      console.log('失败执行了');
      return 'demo';
    }).then(result => {
      // 这里执行了. 由于前面的then返回的是一个'demo'，等同于Promise.resolve
      console.log(result + '05');
      return Promise.reject('抛出新Error')
    }, err => {
      // 未被执行.
    }).catch(err => {
      // 被执行了.
      console.log('catch执行了:' + err);
    }).finally(result => {
      console.log('finally执行了');
    })
    // 执行后的输出结果是:
    // success- 01
    // success- 02
    // success- 03
    // 失败执行了
    // demo05
    // catch执行了:抛出新Error
    // finally执行了

  </script>
</body>

</html>